### ISSUE TITLE
Contact info wrong position

### ISSUE THREAD

**Issue by RANJEETJ06** [dotQ-Research/dotQ-Research.github.io#3]
there is a problem with the web site is 
where i click on contact it opend at this point

<img width="933" alt="Screenshot 2023-08-25 012137" src="https://github.com/dotQ-Research/dotQ-Research.github.io/assets/121615244/788307b8-6e60-42b4-91ef-9fd0a6f67557">

 and that should open at here i.e. the actual contact section

<img width="849" alt="Screenshot 2023-08-25 012213" src="https://github.com/dotQ-Research/dotQ-Research.github.io/assets/121615244/a3eff8e3-1c29-409c-9005-570d25721d71">

**Comment by EnriqueAnguianoVara** [comment]
@RANJEETJ06 Yeah we could put it up and make it more visible, that's a brilliant idea. If you want to do it is all yours

**Comment by RANJEETJ06** [comment]
assign plz

**Comment by EnriqueAnguianoVara** [comment]
@RANJEETJ06 Good job, but you add a vscode plugin that is not necesary
